<?php
/**
 * Created by PhpStorm.
 * User: Maiteh
 * Date: 24/05/16
 * Time: 01:02
 */
/**
 * implement hook_menu_alter
 * @param $items
 * @return mixed
 */
function viago_menu_alter(&$items) {
  $items['user']['type']           = MENU_CALLBACK;
  $items['user/register']['type']  = MENU_CALLBACK;
  $items['user/password']['type']  = MENU_CALLBACK;
  $items['user/login']['type']     = MENU_CALLBACK;
  $items['guide']['type']          = MENU_CALLBACK;
  $items['guide/register']['type'] = MENU_CALLBACK;
  $items['guide/password']['type'] = MENU_CALLBACK;
  $items['guide/login']['type']    = MENU_CALLBACK;

  return $items;
}
/**
 * hook_form_FORM_ID_alter
 */
function viago_form_search_block_form_alter(&$form, &$form_state, $form_id) {
  $form['search_block_form']['#title_display'] = 'invisible'; // Toggle label visibilty

  // Alternative (HTML5) placeholder attribute instead of using the javascript
  $form['search_block_form']['#attributes']['placeholder'] = t('Zoek op Viago');
}